// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ1sN2QAn50QPViP-7vOBWUBxOH2V32XI',
    appId: '1:1006797178797:web:d977fae6f03a2980d94324',
    messagingSenderId: '1006797178797',
    projectId: 'snapkart-2fa40',
    authDomain: 'snapkart-2fa40.firebaseapp.com',
    storageBucket: 'snapkart-2fa40.appspot.com',
    measurementId: 'G-8CB9Y98HRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXASsy9C55ONg8n_KRklOq8qKe2DapOn4',
    appId: '1:1006797178797:android:9df70c8240354ff4d94324',
    messagingSenderId: '1006797178797',
    projectId: 'snapkart-2fa40',
    storageBucket: 'snapkart-2fa40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-jDsG-R6sG_KJQcN5nU99i_gXkTIUAnk',
    appId: '1:1006797178797:ios:cb090fd706654952d94324',
    messagingSenderId: '1006797178797',
    projectId: 'snapkart-2fa40',
    storageBucket: 'snapkart-2fa40.appspot.com',
    iosBundleId: 'com.example.snapkart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-jDsG-R6sG_KJQcN5nU99i_gXkTIUAnk',
    appId: '1:1006797178797:ios:ad9c3f8940fe7814d94324',
    messagingSenderId: '1006797178797',
    projectId: 'snapkart-2fa40',
    storageBucket: 'snapkart-2fa40.appspot.com',
    iosBundleId: 'com.example.snapkart.RunnerTests',
  );
}
